apiVersion: v1
kind: Service
metadata:
  name: flask-hello-service-nodeport

spec:
  type: NodePort
  selector:
    app: flask-hello
    tier: frontend
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30008
